- scripts/generateApis.mjs
- scripts/generateNavigation.mjs
> Update generation scripts to match latest api schema

- public/rivet.schema.json
- scripts/apis/flattenSpec.mjs
- scripts/apis/generateRivetSchema.mjs
- scripts/apis/index.mjs
- scripts/generateGameConfigSchema.mjs
> Game config (rivet.yaml) schema generation

- src/pages/index.jsx
Closes HUB-296
+ additional formatting
> Remove beta indicator from main CTA

- src/components/Header.jsx
- src/components/Navigation.jsx
> Fix navigation mobile design

- src/components/Button.tsx
- src/styles/tailwind.css
- tailwind.config.js
> Bring back working buttons

- game/server/rivet.version.yaml
- src/components/LearnHome.jsx
- src/components/mdx.jsx
- src/pages/docs/general/concepts/dev-tokens.mdx
- src/pages/docs/matchmaker/guides/anti-botting.mdx
- src/pages/docs/matchmaker/guides/custom-games.mdx
- src/pages/learn/godot/tutorials/crash-course/index.mdx
- src/pages/learn/html5/tutorials/crash-course.mdx
- src/pages/learn/html5/tutorials/tanks-canvas-socketio.mdx
- yarn.lock
Fixes WEB-108
Fixes WEB-61
Fixes WEB-109
Fixes WEB-110
> Convert toml to yaml, update HTML5 tutorials, remove old docs

- package.json
- src/app/blog/(posts)/colyseus-arena-end-of-life-migrating-to-rivet-official-colyseus-plugin/page.mdx
- src/app/blog/(posts)/godot-multiplayer-compared-to-unity/page.mdx
- src/mdx/rehype.mjs
- src/pages/learn/godot/tutorials/bomber-demo/index.mdx
- src/pages/learn/godot/tutorials/crash-course/index.mdx
- src/pages/learn/html5/tutorials/tanks-canvas-socketio.mdx
- yarn.lock
> Remove closes beta notes and add gdscript highlighter

- src/pages/docs/matchmaker/concepts/lobby-tags.mdx
> Add code to lobby tags docs

- src/mdx/rehype.mjs
- src/pages/docs/cdn/_navigation.json
- src/pages/docs/cdn/concepts/caching-files.mdx
> Add docs about CDN caching

- src/components/mdx.jsx
- src/pages/docs/dynamic-servers/_navigation.json
- src/pages/docs/dynamic-servers/concepts/host-bridge-networking.mdx
> Document bridge vs host networking

- src/pages/docs/matchmaker/guides/custom-games.mdx
> Add docs on custom game mode publicity

- scripts/apis/generateApiPages.mjs
- scripts/generateNavigation.mjs
- src/components/Header.jsx
- src/components/mdx.jsx
- src/pages/docs/kv/api/delete-batch.mdx
- src/pages/docs/kv/api/delete.mdx
- src/pages/docs/kv/api/get-batch.mdx
- src/pages/docs/kv/api/get.mdx
- src/pages/docs/kv/api/put-batch.mdx
- src/pages/docs/kv/api/put.mdx
- src/pages/docs/kv/index.mdx
- tailwind.config.js
> feat(WEB-60): communicate API stability

- game/server/rivet.version.yaml
- src/pages/learn/godot/tutorials/bomber-demo/index.mdx
- src/pages/learn/godot/tutorials/crash-course/index.mdx
> fix: change godot to rivet.json

- src/mdx/rehype.mjs
> fix: crashing createGameVersion page in docs

- scripts/apis/generateApiPages.mjs
- src/components/mdx.jsx
- src/generated/apiPages.json
- src/pages/docs/core/_navigation.json
- src/pages/docs/core/dynamic-servers/api/builds/complete.mdx
- src/pages/docs/core/dynamic-servers/api/builds/get.mdx
- src/pages/docs/core/dynamic-servers/api/builds/list.mdx
- src/pages/docs/core/dynamic-servers/api/builds/patch-tags.mdx
- src/pages/docs/core/dynamic-servers/api/builds/prepare.mdx
- src/pages/docs/core/dynamic-servers/api/create.mdx
- src/pages/docs/core/dynamic-servers/api/datacenters/list.mdx
- src/pages/docs/core/dynamic-servers/api/get.mdx
- src/pages/docs/core/dynamic-servers/api/list.mdx
- src/pages/docs/core/dynamic-servers/api/logs/get.mdx
- src/pages/docs/core/dynamic-servers/available-regions.mdx
- src/pages/docs/core/dynamic-servers/available-tiers.mdx
- src/pages/docs/core/dynamic-servers/ddos.mdx
- src/pages/docs/core/dynamic-servers/game-guard.mdx
- src/pages/docs/core/dynamic-servers/host-bridge-networking.mdx
- src/pages/docs/core/dynamic-servers/lobby-ready.mdx
- src/pages/docs/core/dynamic-servers/overview.mdx
- src/pages/docs/core/game-tokens/api/create-service-token.mdx
- src/pages/docs/core/index.mdx
- src/pages/docs/general/_navigation.json
- src/pages/docs/general/index.mdx
- src/pages/docs/general/libraries.mdx
> feat: add dynamics servers docs

- src/app/not-found.tsx
- src/components/Game.jsx
- src/pages/index.jsx
> feat: beauty 404 page

- src/components/Search.jsx
> fix: close search after item selection

- scripts/generateNavigation.mjs
- src/components/TableOfContents.jsx
> fix: allow span elements in titles

- src/app/(v2)/docs/[...slug]/page.tsx
- src/app/(v2)/docs/layout.tsx
- src/app/(v2)/modules/[module]/config/page.tsx
- src/app/(v2)/modules/[module]/errors/page.tsx
- src/app/(v2)/modules/[module]/layout.tsx
- src/app/(v2)/modules/[module]/page.tsx
- src/app/(v2)/modules/[module]/scripts/page.tsx
- src/components/DocsNavigation.tsx
- src/components/DocsTableOfContents.tsx
- src/components/Heading.jsx
- src/lib/module.tsx
- tailwind.v2.config.js
> feat: sticky navigation and toc

- src/app/(v2)/docs/[...slug]/page.tsx
- src/app/(v2)/modules/[module]/page.tsx
- src/components/CollapsibleSidebarItem.tsx
- src/components/DocsNavigation.tsx
- src/components/Heading.jsx
- src/components/LearnHome.jsx
- src/components/Resources.jsx
- src/lib/module.tsx
- src/lib/sitemap.ts
> refactor: redesign resource cards
